modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/davidjjung/peepingangels/issues"
license = "MIT License"

[[mods]]
modId = "peeping_angels"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:dirt"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "Raspmary, NCP Bails"
displayURL = "https://modrinth.com/project/peeping-angels"
displayName = "Peeping Angels"
description = '''
    Peepers from Caverns and Chasms only move when their targets don't see them.
    '''

[[mixins]]
config = "peeping_angels.mixins.json"

[[dependencies.peeping_angels]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.peeping_angels]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.peeping_angels]]
modId = "blueprint"
type = "required"

versionRange = "[8.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.peeping_angels]]
modId = "caverns_and_chasms"
type = "required"
versionRange = "[3.0.0,)"
ordering = "AFTER"
side = "BOTH"